@host=http://localhost:3000


### fetch_settings

GET {{host}}/api/admin/settings
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=


### update_settings [AUTH.SAML]

PUT {{host}}/api/admin/settings
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "updates": 
  {
    "auth.saml": 
    {
      "enabled": "true"
    }
  }
}


### fetch_grafana_stats

GET {{host}}/api/admin/stats
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=


### fetch_grafana_usage_report_preview

GET {{host}}/api/admin/usage-report-preview
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=


### create_global_user

POST {{host}}/api/admin/users
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name":"User",
  "email":"user@graf.com",
  "login":"user",
  "password":"userpassword"
}

### delete_user_by_id 
### id is taken from above

DELETE {{host}}/api/admin/users/75
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=
