@host=http://localhost:3000

### get_current_organization

GET {{host}}/api/org/
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=

### test_get_all_users_in_current_organization

GET {{host}}/api/org/users
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=





### create a user

### create_global_user

POST {{host}}/api/admin/users
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name":"User1",
  "email":"user1@graf.com",
  "login":"user1",
  "password":"userpassword"
}

### add_user

POST {{host}}/api/org/users
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
    "role": "Viewer",
    "loginOrEmail": "user1@graf.com"
}


### ADMIN APIS

### get_organization_by_id

GET {{host}}/api/orgs/1
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


### fetch_all_organizations

GET {{host}}/api/orgs
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


### create_organization

POST {{host}}/api/orgs 
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name":"New Org 1",
  "id" : 0
}

### get_users_in_organization

GET {{host}}/api/orgs/1/users
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
