@host=http://localhost:3000

### fetch_users

GET {{host}}/api/users?perpage=10&page=1
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=

### fetch_users

GET {{host}}/api/users
Accept: application/json
Content-Type : application/json
Authorization: Basic YWRtaW46YWRtaW4=


### actual_user

GET {{host}}/api/user 
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
